version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongoUser:mongoPass@mongo:27017/chatApp
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoUser   # Set the username for MongoDB
      MONGO_INITDB_ROOT_PASSWORD: mongoPass   # Set the password for MongoDB
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoUser   # Use the username for MongoDB
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoPass   # Use the password for MongoDB
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_URL: mongodb://mongoUser:mongoPass@mongo:27017/  # The URL Mongo Express will use to connect

volumes:
  mongo-data:
